Powershell Get-EventLog -LogName ^* ^| ForEach {Clear-EventLog $_.log}
schtasks /Change /TN "Microsoft\Windows\Management\Provisioning\Logon" /Disable
schtasks /Change /TN "Microsoft\Windows\Management\Provisioning\Cellular" /Disable
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\appcompat\appraiser' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\appcompat\encapsulation' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\DiagTrack' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\DigitalLocker' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Downloaded Program Files' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\GameBarPresenceWriter' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\LastGood.Tmp' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\LiveKernelReports' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Logs\waasmedic' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\ModemLogs' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Performance' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Panther' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\RemotePackages' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Setup' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\SchCache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\appraiser' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\Logs' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\SysWOW64\Logs' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\LogFiles' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\SysWOW64\LogFiles' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\sru' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\WCN' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\TAPI' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\tracing' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\AMD' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Adobe_backup' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Adobe-Backup' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\InstallShield' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Vault' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\AccountPictures' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Network Shortcuts' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Printer Shortcuts' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Templates' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Start Menu\Programs\Maintenance' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Start Menu\Programs\Accessories' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Mozilla\Firefox\Crash Reports' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Mozilla\Firefox\Pending Pings' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\UXP' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Comms' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Coderbag' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\InputPersonalization' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Vault' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows Sidebar' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\ActionCenterCache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\Application Shortcuts' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\CloudStore' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\GameExplorer' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\Ringtones' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\RoamingTiles' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\SettingSync' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\WER' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Intel' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Diagnosis' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\DiagnosticLogCSP' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\DeviceSync' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\DRM' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\EdgeUpdate' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Event Viewer' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\MapData' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\NetFramework' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Provisioning' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Settings' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\SmsRouter' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Spectrum' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Speech_OneCore' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\WDF' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\WinMSIPC' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\WPD' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\ClipSVC\Install' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\ClipSVC\Import' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\DeviceMetadataCache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\GameExplorer' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\LfSvc' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\OneSettings' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Parental Controls' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Power Efficiency Diagnostics' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\RetailDemo' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Ringtones' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\WER' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\wfp' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Start Menu\Programs\Maintenance' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Start Menu\Programs\Accessibility' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\SoftwareDistribution' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\PerfLogs' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\Microsoft' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\AMD' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\NVIDIA' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\Intel' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\drivers' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\3D Objects' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\Contacts' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\Links' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\IntelGraphicsProfiles' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemRoot%\System32\config\systemprofile\AppData\Local\PlaceholderTileLogoFolder' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemRoot%\System32\config\systemprofile\AppData\Roaming\Leap Motion' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemRoot%\System32\config\Journal' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemRoot%\System32\config\RegBack' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramFiles(x86)%\AMD' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramFiles(x86)%\NVIDIA Corporation' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\Users\Default\NTUSER.DAT_orig' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Temp' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\PlaceholderTileLogoFolder' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\EDP' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\NetTraces' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\gtk-3.0' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\regid.1991-06.com.microsoft' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\WindowsHolographicDevices' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\AppReadiness' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\CbsTemp' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Containers' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\IdentityCRL' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\IME\IMETC' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\IME\IMEKR' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\IME\IMEJP' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\Tasks' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\SysWOW64\Tasks' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\WDI' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\WinBioDatabase' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\NVIDIA' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Credentials' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Internet Explorer\Quick Launch\User Pinned' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\CloudStore' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Start Menu\Programs\Administrative Tools' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Mozilla\Extensions' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Mozilla\SystemExtensionsDev' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\setup' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\ConnectedDevicesPlatform' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\D3DSCache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\IconCache.db' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Credentials' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Internet Explorer' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\WindowsApps' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\AppCache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\Burn' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\Caches' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\Fonts' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\History' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\INetCache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\INetCookies' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\PowerShell' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\WebCache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\PeerDistRepub' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Programs\Common' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\cache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\AppV' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\IdentityCRL' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Network' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Search' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\UEV' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\AppRepository\Families' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows Security Health' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\WwanSvc' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows Defender' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows Defender Advanced Threat Protection' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\DeviceMetadataStore' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\PackagedEventProviders' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Templates' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Mozilla' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\USOShared' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\USOPrivate' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\Favorites' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\Saved Games' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\Searches' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\SoftwareDistribution' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Logs' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Temp' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemRoot%\Temp' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%Temp%' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\*.LOG' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\*.log' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\*.xml' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\*.ini' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\*.db' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\DumpStack.log.*' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\$RECYCLE.BIN' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\*.db' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\Notifications\*.tmp' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemRoot%\System32\config\systemprofile\AppData\Local\*.tmp' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\ElevatedDiagnostics' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\CLR_v2.0' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\CLR_v4.0' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\CLR_v4.0_32' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Event Viewer' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\GameDVR' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\0' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\1024' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\1033' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\Burn' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\Caches' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\INetCache\gimp' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\INetCache\thumbnails' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\INetCache\IE' -Recurse -Force -EA SilentlyContinue -Verbose"
