@echo off
reg add "HKLM\SYSTEM\CurrentControlSet\Services\cdrom" /v "AutoRun" /t REG_DWORD /d "0" /f >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\svsvc" /v "Start" /t REG_DWORD /d "3" /f >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\TimeBrokerSvc" /v "Start" /t REG_DWORD /d "4" /f >nul 2>&1
(net stop "TimeBrokerSvc" /y & sc config "TimeBrokerSvc" start= Disabled) >nul 2>&1
(net stop "beep" /y & sc config "beep" start= Disabled) >nul 2>&1
(net stop "fdPHost" /y & sc config "fdPHost" start= Disabled) >nul 2>&1
(net stop "DusmSvc" /y & sc config "DusmSvc" start= Disabled) >nul 2>&1
(net stop "RasMan" /y & sc config "RasMan" start= Disabled) >nul 2>&1
(net stop "SstpSvc" /y & sc config "SstpSvc" start= Disabled) >nul 2>&1
(net stop "BthAvctpSvc" /y & sc config "BthAvctpSvc" start= Disabled) >nul 2>&1
(net stop "DsmSvc" /y & sc config "DsmSvc" start= Disabled) >nul 2>&1
(net stop "MapsBroker" /y & sc config "MapsBroker" start= Disabled) >nul 2>&1
(net stop "DiagTrack" /y & sc config "DiagTrack" start= Disabled) >nul 2>&1
(net stop "VaultSvc" /y & sc config "VaultSvc" start= Disabled) >nul 2>&1
(net stop "DmEnrollmentSvc" /y & sc config "DmEnrollmentSvc" start= Disabled) >nul 2>&1
(net stop "DPS" /y & sc config "DPS" start= Disabled) >nul 2>&1
(net stop "WdiSystemHost" /y & sc config "WdiSystemHost" start= Disabled) >nul 2>&1
(net stop "DisplayEnhancementService" /y & sc config "DisplayEnhancementService" start= Disabled) >nul 2>&1
(net stop "TrkWks" /y & sc config "TrkWks" start= Disabled) >nul 2>&1
(net stop "lfsvc" /y & sc config "lfsvc" start= Disabled) >nul 2>&1
(net stop "gpsvc" /y & sc config "gpsvc" start= Disabled) >nul 2>&1
(net stop "wlidsvc" /y & sc config "wlidsvc" start= Disabled) >nul 2>&1
(net stop "NgcCtnrSvc" /y & sc config "NgcCtnrSvc" start= Disabled) >nul 2>&1
(net stop "InstallService" /y & sc config "InstallService" start= Disabled) >nul 2>&1
(net stop "Spooler" /y & sc config "Spooler" start= Disabled) >nul 2>&1
(net stop "PcaSvc" /y & sc config "PcaSvc" start= Disabled) >nul 2>&1
(net stop "seclogon" /y & sc config "seclogon" start= Disabled) >nul 2>&1
(net stop "SSDPSRV" /y & sc config "SSDPSRV" start= Disabled) >nul 2>&1
(net stop "SysMain" /y & sc config "SysMain" start= Disabled) >nul 2>&1
(net stop "Themes" /y & sc config "Themes" start= Disabled) >nul 2>&1
(net stop "TabletInputService" /y & sc config "TabletInputService" start= Disabled) >nul 2>&1
(net stop "StiSvc" /y & sc config "StiSvc" start= Disabled) >nul 2>&1
(net stop "WManSvc" /y & sc config "WManSvc" start= Disabled) >nul 2>&1
(net stop "WSearch" /y & sc config "WSearch" start= Disabled) >nul 2>&1
(net stop "LanmanWorkstation" /y & sc config "LanmanWorkstation" start= Disabled) >nul 2>&1
(net stop "XboxGipSvc" /y & sc config "XboxGipSvc" start= Disabled) >nul 2>&1
(net stop "LanmanServer" /y & sc config "LanmanServer" start= Disabled) >nul 2>&1
(net stop "PlugPlay" /y & sc config "PlugPlay" start= Disabled) >nul 2>&1
(net stop "ShellHWDetection" /y & sc config "ShellHWDetection" start= Disabled) >nul 2>&1
(net stop "hidserv" /y & sc config "hidserv" start= Disabled) >nul 2>&1
(net stop "WerSvc" /y & sc config "WerSvc" start= Disabled) >nul 2>&1
(net stop "DoSvc" /y & sc config "DoSvc" start= Disabled) >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\DoSvc" /v "Start" /t REG_DWORD /d "4" /f >nul 2>&1
(net stop "ClipSVC" /y & sc config "ClipSVC" start= Disabled) >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\ClipSVC" /v "Start" /t REG_DWORD /d "4" /f >nul 2>&1
(net stop "cbdhsvc" /y & sc config "cbdhsvc" start= Disabled) >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\cbdhsvc" /v "Start" /t REG_DWORD /d "4" /f >nul 2>&1
(net stop "SgrmBroker" /y & sc config "SgrmBroker" start= Disabled) >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\SgrmBroker" /v "Start" /t REG_DWORD /d "4" /f >nul 2>&1
(net stop "OneSyncSvc" /y & sc config "OneSyncSvc" start= Disabled) >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\OneSyncSvc" /v "Start" /t REG_DWORD /d "4" /f >nul 2>&1
(net stop "dmwappushservice" /y & sc config "dmwappushservice" start= Disabled) >nul 2>&1
(net stop "Parsec" /y & sc config "Parsec" start= Disabled) >nul 2>&1
(net stop "LeapService" /y & sc config "LeapService" start= Disabled) >nul 2>&1
(net stop "TeamViewer" /y & sc config "TeamViewer" start= Disabled) >nul 2>&1
(net stop "AnyDesk" /y & sc config "AnyDesk" start= Disabled) >nul 2>&1
(net stop "McAfee WebAdvisor" /y & sc config "McAfee WebAdvisor" start= Disabled) >nul 2>&1
(net stop "Avira.ServiceHost" /y & sc config "Avira.ServiceHost" start= Disabled) >nul 2>&1
(net stop "AviraOptimizerHost" /y & sc config "AviraOptimizerHost" start= Disabled) >nul 2>&1
(net stop "Avast Tools" /y & sc config "Avast Tools" start= Disabled) >nul 2>&1
(net stop "aswToolsSvc" /y & sc config "aswToolsSvc" start= Disabled) >nul 2>&1
(net stop "aswbIDSAgent" /y & sc config "aswbIDSAgent" start= Disabled) >nul 2>&1
(net stop "AVG TuneUp" /y & sc config "AVG TuneUp" start= Disabled) >nul 2>&1
(net stop "WildTangentService" /y & sc config "WildTangentService" start= Disabled) >nul 2>&1
(net stop "MyWinLockerService" /y & sc config "MyWinLockerService" start= Disabled) >nul 2>&1
(net stop "ePowerSvc" /y & sc config "ePowerSvc" start= Disabled) >nul 2>&1
(net stop "ETDCtrlService" /y & sc config "ETDCtrlService" start= Disabled) >nul 2>&1
(net stop "AdobeUpdateService" /y & sc config "AdobeUpdateService" start= Disabled) >nul 2>&1
(net stop "AdobeARMservice" /y & sc config "AdobeARMservice" start= Disabled) >nul 2>&1
(net stop "AGSService" /y & sc config "AGSService" start= Disabled) >nul 2>&1
(net stop "Wondershare InstallAssist" /y & sc config "Wondershare InstallAssist" start= Disabled) >nul 2>&1
(net stop "Wondershare Helper Compact" /y & sc config "Wondershare Helper Compact" start= Disabled) >nul 2>&1
(net stop "NeroUpdate" /y & sc config "NeroUpdate" start= Disabled) >nul 2>&1
(net stop "CyberLink PowerDVD Service" /y & sc config "CyberLink PowerDVD Service" start= Disabled) >nul 2>&1
(net stop "Corel License Validation Service" /y & sc config "Corel License Validation Service" start= Disabled) >nul 2>&1
(net stop "Corel Update Helper" /y & sc config "Corel Update Helper" start= Disabled) >nul 2>&1
(net stop "BraveElevationService" /y & sc config "BraveElevationService" start= Disabled) >nul 2>&1
(net stop "gupdate" /y & sc config "gupdate" start= Disabled) >nul 2>&1
(net stop "gupdatem" /y & sc config "gupdatem" start= Disabled) >nul 2>&1
(net stop "GoogleCrashHandler" /y & sc config "GoogleCrashHandler" start= Disabled) >nul 2>&1
(net stop "GoogleCrashHandler64" /y & sc config "GoogleCrashHandler64" start= Disabled) >nul 2>&1
(net stop "GoogleChromeElevationService" /y & sc config "GoogleChromeElevationService" start= Disabled) >nul 2>&1
(net stop "GoogleUpdate" /y & sc config "GoogleUpdate" start= Disabled) >nul 2>&1
(net stop "GoogleSoftwareReporterTool" /y & sc config "GoogleSoftwareReporterTool" start= Disabled) >nul 2>&1
(net stop "MozillaMaintenance" /y & sc config "MozillaMaintenance" start= Disabled) >nul 2>&1
(net stop "MicrosoftEdgeElevationService" /y & sc config "MicrosoftEdgeElevationService" start= Disabled) >nul 2>&1
(net stop "edgeupdate" /y & sc config "edgeupdate" start= Disabled) >nul 2>&1
(net stop "edgeupdatem" /y & sc config "edgeupdatem" start= Disabled) >nul 2>&1
(net stop "BingDesktopUpdate" /y & sc config "BingDesktopUpdate" start= Disabled) >nul 2>&1
(net stop "ArmouryCrateService" /y & sc config "ArmouryCrateService" start= Disabled) >nul 2>&1
(net stop "asComSvc" /y & sc config "asComSvc" start= Disabled) >nul 2>&1
(net stop "asus" /y & sc config "asus" start= Disabled) >nul 2>&1
(net stop "asusm" /y & sc config "asusm" start= Disabled) >nul 2>&1
(net stop "AsusCertService" /y & sc config "AsusCertService" start= Disabled) >nul 2>&1
(net stop "AsusROGLSLService" /y & sc config "AsusROGLSLService" start= Disabled) >nul 2>&1
(net stop "LightingService" /y & sc config "LightingService" start= Disabled) >nul 2>&1
(net stop "ROG Live Service" /y & sc config "ROG Live Service" start= Disabled) >nul 2>&1
(net stop "ASUSSoftwareManager" /y & sc config "ASUSSoftwareManager" start= Disabled) >nul 2>&1
(net stop "ASUSSwitch" /y & sc config "ASUSSwitch" start= Disabled) >nul 2>&1
(net stop "ASUSSystemAnalysis" /y & sc config "ASUSSystemAnalysis" start= Disabled) >nul 2>&1
(net stop "ASUSSystemDiagnosis" /y & sc config "ASUSSystemDiagnosis" start= Disabled) >nul 2>&1
(net stop "MSI_Central_Service" /y & sc config "MSI_Central_Service" start= Disabled) >nul 2>&1
(net stop "MSI_Companion_Service" /y & sc config "MSI_Companion_Service" start= Disabled) >nul 2>&1
(net stop "ImControllerService" /y & sc config "ImControllerService" start= Disabled) >nul 2>&1
(net stop "LenovoUtility" /y & sc config "LenovoUtility" start= Disabled) >nul 2>&1
(net stop "LSCNotify" /y & sc config "LSCNotify" start= Disabled) >nul 2>&1
(net stop "LnvAgent" /y & sc config "LnvAgent" start= Disabled) >nul 2>&1
(net stop "Lenovo.Modern.ImController.PluginHost.CompanionApp" /y & sc config "Lenovo.Modern.ImController.PluginHost.CompanionApp" start= Disabled) >nul 2>&1
(net stop "Lenovo.Modern.ImController.PluginHost.Device" /y & sc config "Lenovo.Modern.ImController.PluginHost.Device" start= Disabled) >nul 2>&1
(net stop "Lenovo.Modern.ImController" /y & sc config "Lenovo.Modern.ImController" start= Disabled) >nul 2>&1
(net stop "SupportAssistAgent" /y & sc config "SupportAssistAgent" start= Disabled) >nul 2>&1
(net stop "DellUpService" /y & sc config "DellUpService" start= Disabled) >nul 2>&1
(net stop "AWCCService" /y & sc config "AWCCService" start= Disabled) >nul 2>&1
(net stop "AWCCConsoleService" /y & sc config "AWCCConsoleService" start= Disabled) >nul 2>&1
(net stop "DataVault" /y & sc config "DataVault" start= Disabled) >nul 2>&1
(net stop "DellCustomerConnect" /y & sc config "DellCustomerConnect" start= Disabled) >nul 2>&1
(net stop "Dell.Foundation.Agent" /y & sc config "Dell.Foundation.Agent" start= Disabled) >nul 2>&1
(net stop "nosGetPlusHelper" /y & sc config "nosGetPlusHelper" start= Disabled) >nul 2>&1
(net stop "HPDevHealthService" /y & sc config "HPDevHealthService" start= Disabled) >nul 2>&1
(net stop "HpTouchpointAnalyticsService" /y & sc config "HpTouchpointAnalyticsService" start= Disabled) >nul 2>&1
(net stop "HPSFService" /y & sc config "HPSFService" start= Disabled) >nul 2>&1
(net stop "HPAppHelperCap" /y & sc config "HPAppHelperCap" start= Disabled) >nul 2>&1
(net stop "HPDiagsCap" /y & sc config "HPDiagsCap" start= Disabled) >nul 2>&1
(net stop "HPNetworkCap" /y & sc config "HPNetworkCap" start= Disabled) >nul 2>&1
(net stop "HPSysInfoCap" /y & sc config "HPSysInfoCap" start= Disabled) >nul 2>&1
(net stop "HPPrintScanDoctorService" /y & sc config "HPPrintScanDoctorService" start= Disabled) >nul 2>&1
(net stop "Razer Chroma SDK Server" /y & sc config "Razer Chroma SDK Server" start= Disabled) >nul 2>&1
(net stop "Razer Chroma SDK Service" /y & sc config "Razer Chroma SDK Service" start= Disabled) >nul 2>&1
(net stop "Razer Chroma Stream Server" /y & sc config "Razer Chroma Stream Server" start= Disabled) >nul 2>&1
(net stop "Razer Update Service" /y & sc config "Razer Update Service" start= Disabled) >nul 2>&1
(net stop "RzKLService" /y & sc config "RzKLService" start= Disabled) >nul 2>&1
(net stop "RzThxSrv" /y & sc config "RzThxSrv" start= Disabled) >nul 2>&1
(net stop "Razer Game Scanner" /y & sc config "Razer Game Scanner" start= Disabled) >nul 2>&1
(net stop "CorsairService" /y & sc config "CorsairService" start= Disabled) >nul 2>&1
(net stop "CorsairGamingAudioConfig" /y & sc config "CorsairGamingAudioConfig" start= Disabled) >nul 2>&1
(net stop "CorsairLLAccessService" /y & sc config "CorsairLLAccessService" start= Disabled) >nul 2>&1
(net stop "CorsairVBusDriver" /y & sc config "CorsairVBusDriver" start= Disabled) >nul 2>&1
(net stop "logi_lamparray_service" /y & sc config "logi_lamparray_service" start= Disabled) >nul 2>&1
(net stop "LGHUBUpdaterService" /y & sc config "LGHUBUpdaterService" start= Disabled) >nul 2>&1
(net stop "SteelSeries Engine" /y & sc config "SteelSeries Engine" start= Disabled) >nul 2>&1
(net stop "GvLedService" /y & sc config "GvLedService" start= Disabled) >nul 2>&1
(net stop "GigabyteUpdateService" /y & sc config "GigabyteUpdateService" start= Disabled) >nul 2>&1
(net stop "nebula" /y & sc config "nebula" start= Disabled) >nul 2>&1
(net stop "LGHUBUpdaterService" /y & sc config "LGHUBUpdaterService" start= Disabled) >nul 2>&1
(net stop "Steam Client Service" /y & sc config "Steam Client Service" start= Disabled) >nul 2>&1
(net stop "EABackgroundService" /y & sc config "EABackgroundService" start= Disabled) >nul 2>&1
(net stop "UplayService" /y & sc config "UplayService" start= Disabled) >nul 2>&1
(net stop "EpicOnlineServices" /y & sc config "EpicOnlineServices" start= Disabled) >nul 2>&1
(net stop "RTCore64" /y & sc config "RTCore64" start= Disabled) >nul 2>&1
(net stop "RTCore32" /y & sc config "RTCore32" start= Disabled) >nul 2>&1
(net stop "DropboxUpdate" /y & sc config "DropboxUpdate" start= Disabled) >nul 2>&1
(net stop "OneDriveUpdater" /y & sc config "OneDriveUpdater" start= Disabled) >nul 2>&1
(net stop "IntelTelemetryService" /y & sc config "IntelTelemetryService" start= Disabled) >nul 2>&1
(net stop "Intel(R) Dynamic Tuning Service" /y & sc config "Intel(R) Dynamic Tuning Service" start= Disabled) >nul 2>&1
(net stop "Intel(R) Telemetry Service" /y & sc config "Intel(R) Telemetry Service" start= Disabled) >nul 2>&1
(net stop "DSAService" /y & sc config "DSAService" start= Disabled) >nul 2>&1
(net stop "Intel(R) SUR QC Software Asset Manager" /y & sc config "Intel(R) SUR QC Software Asset Manager" start= Disabled) >nul 2>&1
(net stop "Intel(R) Capability Licensing Service TCP IP Interface" /y & sc config "Intel(R) Capability Licensing Service TCP IP Interface" start= Disabled) >nul 2>&1
(net stop "CCleanerPerformanceOptimizerService" /y & sc config "CCleanerPerformanceOptimizerService" start= Disabled) >nul 2>&1
(net stop "IObitUnSvr" /y & sc config "IObitUnSvr" start= Disabled) >nul 2>&1
(net stop "ASCService" /y & sc config "ASCService" start= Disabled) >nul 2>&1
(net stop "DriverBoosterService" /y & sc config "DriverBoosterService" start= Disabled) >nul 2>&1
(net stop "SmartDefragService" /y & sc config "SmartDefragService" start= Disabled) >nul 2>&1
(net stop "GlaryService" /y & sc config "GlaryService" start= Disabled) >nul 2>&1
(net stop "RetailDemo" /y & sc config "RetailDemo" start= Disabled) >nul 2>&1
(net stop "Killer Network Service" /y & sc config "Killer Network Service" start= Disabled) >nul 2>&1
(net stop "RtkAudioUniversalService" /y & sc config "RtkAudioUniversalService" start= Disabled) >nul 2>&1
(net stop "Amazon Assistant Service" /y & sc config "Amazon Assistant Service" start= Disabled) >nul 2>&1
(net stop "eSupportUpdater" /y & sc config "eSupportUpdater" start= Disabled) >nul 2>&1
(net stop "eSupport Undelete" /y & sc config "eSupport Undelete" start= Disabled) >nul 2>&1
(net stop "ApnUpdater" /y & sc config "ApnUpdater" start= Disabled) >nul 2>&1
(net stop "APNMCP" /y & sc config "APNMCP" start= Disabled) >nul 2>&1
(net stop "AskUpdate" /y & sc config "AskUpdate" start= Disabled) >nul 2>&1
(net stop "YahooAUService" /y & sc config "YahooAUService" start= Disabled) >nul 2>&1
(net stop "YahooUpdater" /y & sc config "YahooUpdater" start= Disabled) >nul 2>&1
(net stop "BingSvc" /y & sc config "BingSvc" start= Disabled) >nul 2>&1
(net stop "SearchAppSvc" /y & sc config "SearchAppSvc" start= Disabled) >nul 2>&1
(net stop "CltMngSvc" /y & sc config "CltMngSvc" start= Disabled) >nul 2>&1
(net stop "CltMngSvcSvc" /y & sc config "CltMngSvcSvc" start= Disabled) >nul 2>&1
(net stop "MyWebSearchService" /y & sc config "MyWebSearchService" start= Disabled) >nul 2>&1
(net stop "BrowserAssistant" /y & sc config "BrowserAssistant" start= Disabled) >nul 2>&1
(net stop "UpdateMgr" /y & sc config "UpdateMgr" start= Disabled) >nul 2>&1
(net stop "SoftwareUpdateService" /y & sc config "SoftwareUpdateService" start= Disabled) >nul 2>&1
(net stop "AppHelperSvc" /y & sc config "AppHelperSvc" start= Disabled) >nul 2>&1
(net stop "BrowserManager" /y & sc config "BrowserManager" start= Disabled) >nul 2>&1
(net stop "SearchProtectService" /y & sc config "SearchProtectService" start= Disabled) >nul 2>&1
(net stop "LavasoftTcpService" /y & sc config "LavasoftTcpService" start= Disabled) >nul 2>&1
(net stop "WebCompanionSvc" /y & sc config "WebCompanionSvc" start= Disabled) >nul 2>&1
(net stop "ConduitSearchSvc" /y & sc config "ConduitSearchSvc" start= Disabled) >nul 2>&1
(net stop "DealPlyLiveUpdateService" /y & sc config "DealPlyLiveUpdateService" start= Disabled) >nul 2>&1
(net stop "BabylonService" /y & sc config "BabylonService" start= Disabled) >nul 2>&1
(net stop "MindsparkService" /y & sc config "MindsparkService" start= Disabled) >nul 2>&1
(net stop "SweetLabsService" /y & sc config "SweetLabsService" start= Disabled) >nul 2>&1
(net stop "LinkurySmartbarService" /y & sc config "LinkurySmartbarService" start= Disabled) >nul 2>&1
(net stop "SpigotUpdaterService" /y & sc config "SpigotUpdaterService" start= Disabled) >nul 2>&1
(net stop "VBoxSDS" /y & sc config "VBoxSDS" start= Disabled) >nul 2>&1
(net stop "NahimicService" /y & sc config "NahimicService" start= Disabled) >nul 2>&1
(net stop "A-Volute.NahimicSrv" /y & sc config "A-Volute.NahimicSrv" start= Disabled) >nul 2>&1
(net stop "DTSAPO3Service" /y & sc config "DTSAPO3Service" start= Disabled) >nul 2>&1
(net stop "DolbyDAXAPI" /y & sc config "DolbyDAXAPI" start= Disabled) >nul 2>&1
(net stop "SENS" /y & sc config "SENS" start= Disabled) >nul 2>&1
(net stop "EventSystem" /y & sc config "EventSystem" start= Demand) >nul 2>&1
(net stop "PhoneSvc" /y & sc config "PhoneSvc" start= Disabled) >nul 2>&1
